name: NPM Trusted Publication

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-json-file-path:
        required: false
        type: string
        default: package.json
      publish-workflow:
        required: true
        type: string
      repository:
        required: true
        type: string
      github-environment:
        required: true
        type: string
        default: npm-publish

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24.14.1'
          registry-url: https://registry.npmjs.org

      - uses: ./.github/actions/npm-trusted-publication
        with:
          package-name: ${{ inputs.package-name }}
          package-json-file-path: ${{ inputs.package-json-file-path }}
          publish-workflow: ${{ inputs.publish-workflow }}
          repository: ${{ inputs.repository }}
          github-environment: ${{ inputs.github-environment }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOTP_DEVICE: ${{ secrets.NPM_TOTP_DEVICE }}
