name: Ruby Gem

on:
  workflow_call:
    inputs:
      ruby_version:
        required: false
        type: string
        default: '2.6'
    secrets:
      RUBY_GEMS_API_KEY:
        required: true
      RUBY_GEMS_TOTP_DEVICE:
        required: true

jobs:
  build:
    name: Build + Publish
    runs-on: [ubuntu-latest]
    environment: rubygems-publish
    steps:
    - uses: zendesk/checkout@v3
    - name: Set up Ruby
      uses: zendesk/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}

    - name: Install oauth
      run: |
        sudo apt-get install --fix-broken --yes oathtool

    - name: Publish to RubyGems
      run: |
        gem build *.gemspec
        totp=$(oathtool --base32 --totp "${RUBY_GEMS_TOTP_DEVICE}")
        gem push *.gem --otp "$totp"
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBY_GEMS_API_KEY }}
        RUBY_GEMS_TOTP_DEVICE: ${{ secrets.RUBY_GEMS_TOTP_DEVICE }}
